version: "2"
services:
  portal:
    build: ./services/app
    volumes:
      - ./services:/services
      - ./data/log/portal:/root/.pm2/logs
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "80:80"
  monitor:
    build: ./services/monitor
    volumes:
      - ./services:/services
      - ./data/log/monitor:/root/.pm2/logs
    depends_on:
      - mongo
    links:
      - mongo
  cron:
    build: ./services/cron
    volumes:
      - ./services:/services
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME:monitor
      - MONGO_INITDB_ROOT_PASSWORD:m0n1t0r
      - MONGO_INITDB_DATABASE:monitor
    ports:
      - "27017:27017"
