version: "2"
services:
  portal:
    build: ./services/app
    volumes:
      - ./services:/services
      - ./data/log/portal:/root/.pm2/logs
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "80:80"
  monitor:
    build: ./services/monitor
    volumes:
      - ./services:/services
      - ./data/log/monitor:/root/.pm2/logs
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data/db/mongo:/data/db
    ports:
      - "27017:27017"
